spp-platform:
  host: ${SPP_PLATFORM_HOST:-0.0.0.0}
  port: ${SPP_PLATFORM_PORT:-5445}
  access_token: ${SPP_SYSTEM_ACCESS_TOKEN:-change-me}
  logging:
    level: ${SPP_LOGGING_LEVEL:-info}
  probe:
    bridge_port: ${SPP_PROBE_BRIDGE_PORT:-5450}
  marker:
    bridge_port: ${SPP_MARKER_BRIDGE_PORT:-5455}
  processor:
    bridge_port: ${SPP_PROCESSOR_BRIDGE_PORT:-5460}
    live-instrument:
      enabled: ${SPP_PROCESSOR_LIVE_INSTRUMENT_ENABLED:-true}
    live-view:
      enabled: ${SPP_PROCESSOR_LIVE_VIEW_ENABLED:-true}

storage:
  selector: ${SPP_STORAGE:-memory}
  redis:
    host: ${SPP_REDIS_HOST:-localhost}
    port: ${SPP_REDIS_PORT:-6379}

skywalking-oap:
  host: ${SPP_OAP_HOST:-localhost}
  port: ${SPP_OAP_PORT:-12800}
