version: '3.3'
services:
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
    environment:
      - SPP_DISABLE_TLS=true
      - SPP_DISABLE_JWT=true
  skywalking-oap:
    image: sourceplusplus/spp-oap-server:latest
    container_name: skywalking-oap
    hostname: skywalking-oap
    environment:
      - SPP_PLATFORM_HOST=spp-platform
      - SPP_PLATFORM_PORT=5460
      - SPP_DISABLE_TLS=true
