spp-platform:
  host: 0.0.0.0
  port: 5445
  access_token: "change-me"
  logging:
    level: info
  probe:
    bridge_port: 5450
  marker:
    bridge_port: 5455
  processor:
    bridge_port: 5460

redis:
  host: localhost
  port: 6379

skywalking-oap:
  host: localhost
  port: 12800
