version: '3.3'
services:
  spp-platform:
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
      - "5450:5450"
      - "5455:5455"
      #- "5107:5107"
    build:
      context: .
      dockerfile: Dockerfile-spp-platform-mini
    depends_on:
      - redis
    links:
      - redis
    environment:
      - SPP_SYSTEM_ACCESS_TOKEN=change-me
  redis:
    image: redis:6.2.1
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  skywalking-oap:
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "11800:11800"
      - "12800:12800"
      #- "5106:5106"
    build:
      context: .
      dockerfile: Dockerfile-skywalking-oap
    depends_on:
      - es-server
    links:
      - es-server
    restart: on-failure
    environment:
      - SW_STORAGE=elasticsearch7
      - SW_STORAGE_ES_CLUSTER_NODES=es-server:9200
      #- JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5106
  spp-example-webapp:
    container_name: spp-example-webapp
    hostname: spp-example-webapp
#    ports:
#      - "5105:5105"
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    build:
      context: .
      dockerfile: Dockerfile-spp-example-webapp
  es-server:
    image: blacktop/elasticsearch:7.0.0
    container_name: es-server
    hostname: es-server
    ports:
      - "9200:9200"
      - "9300:9300"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    command: -E cluster.name=es-skywalking -E path.data=data -E path.logs=logs -E network.host=0.0.0.0 -E node.name=node-1
#  skywalking-ui:
#    image: apache/skywalking-ui:8.6.0
#    container_name: skywalking-ui
#    hostname: skywalking-ui
#    ports:
#      - "8888:8080"
#    depends_on:
#      - skywalking-oap
#    links:
#      - skywalking-oap
#    environment:
#      - SW_OAP_ADDRESS=skywalking-oap:12800
